# Generated by Django 2.2.6 on 2019-10-11 18:26

from django.db import migrations


def supply_default_menu(apps, schema_editor):
    """
    Create some default menu items
    """
    MenuItem = apps.get_model("menu", "MenuItem")
    my_favorite_foods = [
        {"name": "Posole", "price": 4.99},
        {"name": "Menudo", "price": 3.49},
        {"name": "Nachos", "price": 3.99},
        {"name": "Chicken Enchiladas", "price": 7.99},
        {"name": "Veggie Enchiladas", "price": 6.99},
        {"name": "Churros", "price": 2.99},
    ]
    for food_dict in my_favorite_foods:
        instance = MenuItem(**food_dict)
        instance.save()


class Migration(migrations.Migration):

    dependencies = [("menu", "0001_initial")]

    operations = [
        migrations.RunPython(
            supply_default_menu, reverse_code=migrations.RunPython.noop
        )
    ]
